hotelSpa/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::get('login','LoginController@index');
Route::post('login','LoginController@login');
Route::get('logout','LoginController@logout');

//Route::get('redirect','RedirectController@index');

/* Actividades */

Route::get('actividades/masajista', 'MasajistaController@index');
Route::post('actividades/masajista', 'MasajistaController@create');

Route::get('actividades/conferencias','ConferenciasController@index');
Route::post('actividades/conferencias','ConferenciasController@create');

Route::get('actividades/spa','SpaController@index');
Route::post('actividades/spa','SpaController@create');

Route::get('actividades/gimnasio','GimnasioController@index');
Route::post('actividades/gimnasio','GimnasioController@create');

/* Servicios */

Route::get('servicios/comida','ComidaController@index');
Route::post('servicios/comida','ComidaController@create');

Route::get('servicios/despertador','DespertadorController@index');
Route::post('servicios/despertador','DespertadorController@create');

Route::get('servicios/limpieza','LimpiezaController@index');
Route::post('servicios/limpieza','LimpiezaController@create');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

/* Get del Panel de Administracion */

Route::get('admin/clientes','UsuarioController@admin_clientes');

Route::get('admin/clientes/crear','UsuarioController@create');

Route::get('admin/actividades','ActividadController@admin_actividades');

Route::get('admin/actividades/crear','ActividadController@create');

Route::get('admin/servicios','ServicioController@admin_servicios');

Route::get('admin/servicios/crear','ServicioController@create');

/* Fin del Panel de Administracion */

/*-- Recursos --*/

Route::get('admin','FrontController@admin');

Route::resource('usuario','UsuarioController');

Route::resource('actividad','ActividadController');

Route::resource('servicio','ServicioController');

/*-- Fin de Recursos --*/

/*-- PDF --*/

Route::resource('pdf','PdfController');

/*-- PDF --*/

hotelSpa/resources/views/admin/admin_actividades.blade.php
@extends('layouts.admintempl')
@section('content')

@if(Session::has('message'))
	<div class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span ariahidden="true">&times;</span></button>
		{{Session::get('message')}}
	</div>
@endif

<div class="mother-grid-inner">
             <!--header start here-->
				<div class="header-main">
					<ol class="breadcrumb">
                		<li class="breadcrumb-item"><a href="{!!URL::to('/admin')!!}">Inicio </a> <i class="fa fa-angle-right"></i></li>
						<li class="breadcrumb-item"><a href="{!!URL::to('/admin/actividades')!!}">Actividades</a> <i class="fa fa-angle-right"></i></li>
            		</ol>
				</div>
</div>

<table class="table">
	<thead>
		<th>ID</th>
		<th>Actividad</th>
		<th>ID Cliente</th>
		<th>Fecha</th>
		<th>Operacion</th>
	</thead>	

	@foreach($m_actividades as $actividad)
	<tbody>
		<td>{{$actividad->id}}</td>
		<td>{{$actividad->actividad}}</td>
		<td>{{$actividad->id_cliente}}</td>
		<td>{{$actividad->fecha}}</td>
		<td>{!!link_to_route('actividad.edit', $title = 'Modificar', $parameters = $actividad->id, $attributes= ['class'=>'btn btn-primary'])!!}</td>	
	</tbody>
	@endforeach

</table>

@stop

hotelSpa/resources/views/admin/admin_clientes.blade.php
@extends('layouts.admintempl')
@section('content')

@if(Session::has('message'))
	<div class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span ariahidden="true">&times;</span></button>
		{{Session::get('message')}}
	</div>
@endif

<div class="mother-grid-inner">
             <!--header start here-->
				<div class="header-main">
					<ol class="breadcrumb">
                		<li class="breadcrumb-item"><a href="{!!URL::to('/admin')!!}">Inicio </a> <i class="fa fa-angle-right"></i></li>
						<li class="breadcrumb-item"><a href="{!!URL::to('/admin/clientes')!!}">Clientes</a> <i class="fa fa-angle-right"></i></li>
            		</ol>
				</div>
</div>

<table class="table">
	<thead>
		<th>ID</th>
		<th>DNI</th>
		<th>Habit</th>
		<th>Operacion</th>
		<th>Ver PDF</th>
	</thead>	

	@foreach($users as $user)
	@if ($user->dni !== "12345678X")
	<tbody>
		<td>{{$user->id}}</td>
		<td>{{$user->dni}}</td>
		<td>{{$user->habit}}</td>
		<td>{!!link_to_route('usuario.edit', $title = 'Modificar', $parameters = $user->id, $attributes= ['class'=>'btn btn-primary'])!!}</td>
		<td>{!!link_to_route('pdf.edit', $title = 'Crear PDF', $parameters = $user->id, $attributes= ['class'=>'btn btn-info'])!!}</td>
	</tbody>
	@endif
	@endforeach

</table>

@stop

hotelSpa/resources/views/admin/admin_crear_actividades.blade.php
@extends('layouts.admintempl')
@section('content')

@if(Session::has('message'))
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span ariahidden="true">&times;</span></button>
		{{Session::get('message')}}
	</div>
@endif

<div class="mother-grid-inner">
	<div class="header-main">
		<ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin')!!}">Inicio</a> <i class="fa fa-angle-right"></i></li>
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin/actividades')!!}">Actividades</a> <i class="fa fa-angle-right"></i></li>
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin/actividades/crear')!!}">Crear actividades</a> <i class="fa fa-angle-right"></i></li>
        </ol>
	</div>
</div>

<br>

{!!Form::open(['route'=>'actividad.store', 'method'=>'POST'])!!}

	@include('admin.admin_forms.forms_actividades')
	
	{!!Form::submit('Insertar',['class'=>"btn btn-primary"])!!}
{!!Form::close()!!}

<br>

@stop

hotelSpa/resources/views/admin/admin_crear_clientes.blade.php
@extends('layouts.admintempl')
@section('content')

@if(Session::has('message'))
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span ariahidden="true">&times;</span></button>
		{{Session::get('message')}}
	</div>
@endif

<br>

<div class="mother-grid-inner">
	<div class="header-main">
		<ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin')!!}">Inicio</a> <i class="fa fa-angle-right"></i></li>
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin/clientes')!!}">Clientes</a> <i class="fa fa-angle-right"></i></li>
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin/clientes/crear')!!}">Crear clientes</a> <i class="fa fa-angle-right"></i></li>
        </ol>
	</div>
</div>

<br>

{!!Form::open(['route'=>'usuario.store', 'method'=>'POST'])!!}

	@include('admin.admin_forms.forms_user')
	
	{!!Form::submit('Insertar',['class'=>"btn btn-primary"])!!}
{!!Form::close()!!}

<br>

@stop

hotelSpa/resources/views/admin/admin_crear_servicios.blade.php
@extends('layouts.admintempl')
@section('content')

<div class="mother-grid-inner">
	<div class="header-main">
		<ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin')!!}">Inicio</a> <i class="fa fa-angle-right"></i></li>
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin/servicios')!!}">Servicios</a> <i class="fa fa-angle-right"></i></li>
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin/servicios/crear')!!}">Crear servicios</a> <i class="fa fa-angle-right"></i></li>
        </ol>
	</div>
</div>

<br>

{!!Form::open(['route'=>'servicio.store', 'method'=>'POST'])!!}

	@include('admin.admin_forms.forms_servicios')
	
	{!!Form::submit('Insertar',['class'=>"btn btn-primary"])!!}
{!!Form::close()!!}

<br>

@stop

hotelSpa/resources/views/admin/admin_modificar_actividades.blade.php
@extends('layouts.admintempl')
@section('content')

@if(Session::has('message'))
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span ariahidden="true">&times;</span></button>
		{{Session::get('message')}}
	</div>
@endif

<div class="mother-grid-inner">
	<div class="header-main">
		<ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin')!!}">Inicio</a> <i class="fa fa-angle-right"></i></li>
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin/actividades')!!}">Actividades</a> <i class="fa fa-angle-right"></i></li>
            <li class="breadcrumb-item"><a href="#">Modificar actividades</a> <i class="fa fa-angle-right"></i></li>
        </ol>
	</div>
</div>

<br>

{!!Form::model($activi, ['route' => ['actividad.update',$activi->id], 'method'=>'PUT'])!!}

	@include('admin.admin_forms.forms_actividades')
	<div class="formcustom">
	{!!Form::submit('Actualizar',['class'=>"btn btn-primary"])!!}

	{!!Form::close()!!}
	{!!Form::open(['route' => ['actividad.destroy',$activi->id], 'method'=>'DELETE'])!!} 

	{!!Form::submit('Eliminar',['class'=>"btn btn-danger"])!!} 
	</div>
	{!!Form::close()!!}
	<br>

@stop

hotelSpa/resources/views/admin/admin_modificar_clientes.blade.php
@extends('layouts.admintempl')
@section('content')

@if(Session::has('message'))
	<div class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span ariahidden="true">&times;</span></button>
		{{Session::get('message')}}
	</div>
@endif

<div class="mother-grid-inner">
	<div class="header-main">
		<ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin')!!}">Inicio</a> <i class="fa fa-angle-right"></i></li>
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin/clientes')!!}">Clientes</a> <i class="fa fa-angle-right"></i></li>
            <li class="breadcrumb-item"><a href="#">Modificar clientes</a> <i class="fa fa-angle-right"></i></li>
        </ol>
	</div>
</div>

<br>

{!!Form::model($user, ['route' => ['usuario.update',$user->id], 'method'=>'PUT'])!!}

	@include('admin.admin_forms.forms_user')
	<div class="formcustom">
	{!!Form::submit('Actualizar',['class'=>"btn btn-primary"])!!}

	{!!Form::close()!!}

	{!!Form::open(['route' => ['usuario.destroy',$user->id], 'method'=>'DELETE'])!!} 

	{!!Form::submit('Eliminar',['class'=>"btn btn-danger"])!!} 
	</div>
	{!!Form::close()!!}
	<br>

@stop

hotelSpa/resources/views/admin/admin_modificar_servicios.blade.php
@extends('layouts.admintempl')
@section('content')

<div class="mother-grid-inner">
	<div class="header-main">
		<ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin')!!}">Inicio</a> <i class="fa fa-angle-right"></i></li>
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin/servicios')!!}">Servicios</a> <i class="fa fa-angle-right"></i></li>
            <li class="breadcrumb-item"><a href="#">Modificar servicios</a> <i class="fa fa-angle-right"></i></li>
        </ol>
	</div>
</div>

<br>

{!!Form::model($serv, ['route' => ['servicio.update',$serv->id], 'method'=>'PUT'])!!}

	@include('admin.admin_forms.forms_servicios')
	<div class="formcustom">
	{!!Form::submit('Actualizar',['class'=>"btn btn-primary"])!!}

	{!!Form::close()!!}

	{!!Form::open(['route' => ['servicio.destroy',$serv->id], 'method'=>'DELETE'])!!} 

	{!!Form::submit('Eliminar',['class'=>"btn btn-danger"])!!} 
	</div>
	{!!Form::close()!!}
	<br>

@stop

hotelSpa/resources/views/admin/admin_servicios.blade.php
@extends('layouts.admintempl')
@section('content')

@if(Session::has('message'))
	<div class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span ariahidden="true">&times;</span></button>
		{{Session::get('message')}}
	</div>
@endif

<div class="mother-grid-inner">
             <!--header start here-->
				<div class="header-main">
					<ol class="breadcrumb">
                		<li class="breadcrumb-item"><a href="{!!URL::to('/admin')!!}">Inicio </a> <i class="fa fa-angle-right"></i></li>
						<li class="breadcrumb-item"><a href="{!!URL::to('/admin/actividades')!!}">Actividades</a> <i class="fa fa-angle-right"></i></li>
            		</ol>
				</div>
</div>

<table class="table">
	<thead>
		<th>ID</th>
		<th>Servicio</th>
		<th>ID Cliente</th>
		<th>Observacion</th>
		<th>Operacion</th>
	</thead>	

	@foreach($m_servicios as $servicio)
	<tbody>
		<td>{{$servicio->id}}</td>
		<td>{{$servicio->serv}}</td>
		<td>{{$servicio->id_cliente}}</td>
		<td>{{$servicio->observacion}}</td>
		<td>{!!link_to_route('servicio.edit', $title = 'Modificar', $parameters = $servicio->id, $attributes= ['class'=>'btn btn-primary'])!!}</td>	
	</tbody>
	@endforeach

</table>

@stop

hotelSpa/resources/views/admin/index.blade.php
@extends('layouts.admintempl')
@section('content')

<div class="mother-grid-inner">
	<div class="header-main">
		<ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{!!URL::to('/admin')!!}">Inicio</a> <i class="fa fa-angle-right"></i></li>
        </ol>
	</div>
</div>

<br>

<div class="container">
	<div class="row">
		<div class="col-md-10">
			<div class="panel-heading">
			<h1>Panel de administración</h1>
			</div>
		</div>
	</div>
</div>

@stop